services:
  database:
    build: ./database
    container_name: postgres-db
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: usr
      POSTGRES_PASSWORD: pwd
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    restart: unless-stopped

  backend:
    build: ./backend
    container_name: my-backend-container
    depends_on:
      - database
    networks:
      - app-network
    restart: unless-stopped


  httpd:
    build: ./httpd
    container_name: my-httpd-container
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - app-network
    restart: unless-stopped

networks:
  app-network:

volumes:
  pgdata: