name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  build-and-push-docker:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Detect changes
      - name: Detect changes
        id: changes
        uses: dorny/paths-filter@v3
        with:
          filters: |
            backend:
              - 'backend/**'
            database:
              - 'database/**'
            httpd:
              - 'httpd/**'

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login --username "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build and push backend image
        if: steps.changes.outputs.backend == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-backend:latest

      - name: Build and push database image
        if: steps.changes.outputs.database == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./database
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-database:latest

      - name: Build and push httpd image
        if: steps.changes.outputs.httpd == 'true'
        uses: docker/build-push-action@v6
        with:
          context: ./httpd
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/tp-devops-httpd:latest